AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Website:
    Type: AWS::CodeBuild::Project
    DependsOn: WebsiteRole
    Properties:
      Name: !Sub ${AWS::StackName}-Website
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: SOURCE_DIRECTORY
            Value: src/site
          - Name: BUILD_COMMAND
            Value: npm build
          - Name: PUBLISH_DIRECTORY
            Value: src/site/public
          - Name: SOURCE_LOCATION
            Value: !Ref SourceLocation
          - Name: SOURCE_VERSION
            Value: !Ref SourceVersion
          - Name: DESTINATION_BUCKET_NAME
            Value: !Ref Bucket
      ServiceRole: !GetAtt WebsiteRole.Arn
      Source:
        Type: NO_SOURCE
        BuildSpec: |-
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: latest
                python: latest
                ruby: latest
              commands:
                - aws s3 cp "${SOURCE_LOCATION}" - | tar xz || git clone "${SOURCE_LOCATION}" .
                - cd '${SOURCE_DIRECTORY}'
                - [ -f yarn.lock ] && npm install -g yarn
                - touch /tmp/buildphase-install-success
              finally:
                - [ ! -f /tmp/buildphase-install-success ] && curl -X PUT ${CFN_RESPONSE_URL} "{\"Status\":\"FAILED\",\"Reason\":\"Failed to install runtime dependencies\",\"PhysicalResourceId\":\"${SOURCE_VERSION}\",\"StackId\":\"${CFN_STACK_ID}\",\"RequestId\":\"${CFN_REQUEST_ID}\",\"LogicalResourceId\":\"${CFN_LOGICAL_ID}\"}"
            pre_build:
                - cd '${SOURCE_DIRECTORY}'
                - [ ! -f yarn.lock -a -f package.json ] && npm install --production
                - [ -f yarn.lock ] && yarn install --production
                - [ -f requirements.txt ] && pip install -r requirements.txt
                - [ -f Gemfile ] && bundle install
                - touch /tmp/buildphase-pre_build-success
              finally:
                - [ ! -f /tmp/buildphase-pre_build-success ] && curl -X PUT ${CFN_RESPONSE_URL} "{\"Status\":\"FAILED\",\"Reason\":\"Failed to install site dependencies\",\"PhysicalResourceId\":\"${SOURCE_VERSION}\",\"StackId\":\"${CFN_STACK_ID}\",\"RequestId\":\"${CFN_REQUEST_ID}\",\"LogicalResourceId\":\"${CFN_LOGICAL_ID}\"}"
            build:
              commands:
                - cd '${SOURCE_DIRECTORY}'
                - ${BUILD_COMMAND}
                - touch /tmp/buildphase-build-success
              finally:
                - [ ! -f /tmp/buildphase-build-success ] && curl -X PUT ${CFN_RESPONSE_URL} "{\"Status\":\"FAILED\",\"Reason\":\"Failed to build site",\"PhysicalResourceId\":\"${SOURCE_VERSION}\",\"StackId\":\"${CFN_STACK_ID}\",\"RequestId\":\"${CFN_REQUEST_ID}\",\"LogicalResourceId\":\"${CFN_LOGICAL_ID}\"}"
            post_build:
              commands:
                - aws s3 sync '${PUBLISH_DIRECTORY}' 's3://${DESTINATION_BUCKET_NAME}/' --acl public-read --cache-control 'max-age=0, must-revalidate, public' --no-progress --delete
                - curl -X PUT ${CFN_RESPONSE_URL} "{\"Status\":\"SUCCESS\",\"PhysicalResourceId\":\"${SOURCE_VERSION}\",\"StackId\":\"\${CFN_STACK_ID}\",\"RequestId\":\"${CFN_REQUEST_ID}\",\"LogicalResourceId\":\"${CFN_LOGICAL_ID}\"}"
                - touch /tmp/buildphase-post_build-success
              finally:
                - [ ! -f /tmp/buildphase-post_build-success ] && curl -X PUT ${CFN_RESPONSE_URL} "{\"Status\":\"FAILED\",\"Reason\":\"Failed to publish site\",\"PhysicalResourceId\":\"${SOURCE_VERSION}\",\"StackId\":\"${CFN_STACK_ID}\",\"RequestId\":\"${CFN_REQUEST_ID}\",\"LogicalResourceId\":\"${CFN_LOGICAL_ID}\"}"
      Tags:
        - Key: Stackery Project Type
          Value: Website Builder
  WebsiteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-Website
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: Logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-Website:log-stream:*
        - PolicyName: DownloadSourceFromStackeryAssetsBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: arn:aws:s3:::stackery-assetsbucket-*/*
        - PolicyName: UploadToDestinationObjectStore
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub ${Bucket.Arn}/*
  WebsiteBuildTrigger:
    Type: Custom::StackeryWebsiteBuildTrigger
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: website
      ProjectName: !Ref Website
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-bucket-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
Parameters:
  SourceLocation:
    Type: String
    Description: Location of source code for deployment (injected by Stackery at deployment time)
  SourceVersion:
    Type: String
    Description: Source version for deployment (injected by Stackery at deployment time)